// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ6hMvLjpoZr4y8F9sIi4POlGMoVVonjo',
    appId: '1:709971882252:web:7441e08ec704d41f3c5929',
    messagingSenderId: '709971882252',
    projectId: 'adv-ecommerce-app',
    authDomain: 'adv-ecommerce-app.firebaseapp.com',
    storageBucket: 'adv-ecommerce-app.appspot.com',
    measurementId: 'G-4EQH95E49Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKSe_y2rjcvgCrELjYlR_zyrl8mzdmolc',
    appId: '1:709971882252:android:b27364739dda36723c5929',
    messagingSenderId: '709971882252',
    projectId: 'adv-ecommerce-app',
    storageBucket: 'adv-ecommerce-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaWtoRYFkpD-TvGfmtix_y0gunVN31OJ0',
    appId: '1:709971882252:ios:337dd286597ac52f3c5929',
    messagingSenderId: '709971882252',
    projectId: 'adv-ecommerce-app',
    storageBucket: 'adv-ecommerce-app.appspot.com',
    iosBundleId: 'com.example.advEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaWtoRYFkpD-TvGfmtix_y0gunVN31OJ0',
    appId: '1:709971882252:ios:517a824a9edebbd63c5929',
    messagingSenderId: '709971882252',
    projectId: 'adv-ecommerce-app',
    storageBucket: 'adv-ecommerce-app.appspot.com',
    iosBundleId: 'com.example.advEcommerceApp.RunnerTests',
  );
}
